version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
  go:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    
    depends_on:
      - redis
  
volumes:
  redis-data:
   driver: local